# Generated by Django 4.2 on 2023-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_like_body_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
