# Generated by Django 4.2.1 on 2023-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
