# Generated by Django 4.2.1 on 2023-05-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postattachment_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='is_private',
        ),
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
